blueprint:
  name: cover_position_FIX_TS130F (Multi-Device)
  description: Fix roller shutter states according to their current position for multiple covers
  domain: automation
  input:
    cover_entities:
      name: "🏠 Covers"
      description: Which blinds or roller shutters should be fixed (select multiple)
      selector:
        entity:
          multiple: true
          filter:
            - domain: cover

triggers:
  - trigger: numeric_state
    entity_id: !input cover_entities
    attribute: current_position
    below: 1
    id: COVER_CLOSED
  - trigger: numeric_state
    entity_id: !input cover_entities
    attribute: current_position
    above: 99
    id: COVER_OPENED

conditions: []

actions:
  - choose:
      - conditions:
          - condition: trigger
            id: COVER_CLOSED
        sequence:
          - action: cover.close_cover
            target:
              entity_id: "{{ trigger.entity_id }}"
      - conditions:
          - condition: trigger
            id: COVER_OPENED
        sequence:
          - action: cover.open_cover
            target:
              entity_id: "{{ trigger.entity_id }}"

mode: parallel
max: 16
